name: 编译Agent

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc]
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{ matrix.target }}

    - name: Install vcpkg and dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe install opus:x64-windows
        .\vcpkg\vcpkg.exe install libvpx:x64-windows-static
      shell: pwsh

    - name: Set VCPKG_ROOT
      run: echo "VCPKG_ROOT=${{ github.workspace }}\vcpkg" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Set VCPKG_DEFAULT_TRIPLET
      run: echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Symlink opus include to static path
      run: |
        New-Item -ItemType Directory -Force -Path .\vcpkg\installed\x64-windows-static
        cmd /c mklink /D .\vcpkg\installed\x64-windows-static\include .\vcpkg\installed\x64-windows\include
        cmd /c mklink /D .\vcpkg\installed\x64-windows-static\lib .\vcpkg\installed\x64-windows\lib
      shell: pwsh

    - name: Install LLVM for bindgen
      run: choco install llvm -y
      shell: pwsh

    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          agent_src/target
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('agent_src/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build (Release)
      working-directory: agent_src
      run: cargo build --release --verbose

    - name: Run Tests
      working-directory: agent_src
      run: cargo test --verbose

    - name: Run Integration Tests
      working-directory: agent_src
      run: cargo test --release --verbose

    - name: Upload Release Artifacts
      if: matrix.target == 'x86_64-pc-windows-msvc'
      uses: actions/upload-artifact@v4
      with:
        name: release-bin
        path: |
          agent_src/target/release/agent.exe

    - name: List opus include files
      run: Get-ChildItem -Recurse .\vcpkg\installed\x64-windows\include
      shell: pwsh
